import axios from "axios";
import Head from "next/head";
import { Video } from "../../types";
import NoResults from "../components/NoResults";
import VideoCard from "../components/VideoCard";

interface IProps {
  videos: Video[];
}

export default function Home({ videos }: IProps) {
  return (
    <>
      <Head>
        <title>Cliphop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="videos flex h-full flex-col gap-10">
        {videos.length ? (
          videos.map((video) => {
            return <VideoCard post={video} key={video._id}></VideoCard>;
          })
        ) : (
          <NoResults text={"No Videos"}></NoResults>
        )}
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(
    `${process.env.NEXT_PUBLIC_API_BASE_URL}/post`
  );

  return {
    props: {
      videos: data,
    },
  };
};
